version: '3'
services:
  database:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'financasdb'
      MYSQL_USER: 'jjuser'
      MYSQL_PASSWORD: 'passwordfinancas'
      MYSQL_ROOT_PASSWORD: 'passwordfinancas'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
