version: '3'
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mangadb'
      MYSQL_USER: 'jjuser'
      MYSQL_PASSWORD: 'manga-jj-password'
      MYSQL_ROOT_PASSWORD: 'manga-jj-password'
      ports:
        - 3306:3306
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
