INSERT INTO CATEGORIA(ID, NOME) VALUES (1, 'Alimentação');
INSERT INTO CATEGORIA(ID, NOME) VALUES (2, 'Saúde');
INSERT INTO CATEGORIA(ID, NOME) VALUES (3, 'Moradia');
INSERT INTO CATEGORIA(ID, NOME) VALUES (4, 'Transporte');
INSERT INTO CATEGORIA(ID, NOME) VALUES (5, 'Educação');
INSERT INTO CATEGORIA(ID, NOME) VALUES (6, 'Lazer');
INSERT INTO CATEGORIA(ID, NOME) VALUES (7, 'Imprevistos');
INSERT INTO CATEGORIA(ID, NOME) VALUES (8, 'Outras');